### ISSUE TITLE
SC connectivity is checked each time an audit message is to be sent

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl.Plugin.Nsb5.SagaAudit#5]
### Symptoms

An instance of `ServiceControlBackend` is created each time the plugin sends out the saga audit message which means each time it is used it checks the connectivity resulting in an unnecessary empty message. This message should only be sent once, when initializing.
### Who's affected

Everybody

**Comment by SimonCropp** [comment]
note this needs to be fixed in the Nsb4 and Nsb5 versions of this repository as well
